[tool.pytest.ini_options]

pythonpath= "."
addopts = "-v --black --isort --cov=function_module/  --cov=main"
filterwarnings = [
    "default::DeprecationWarning:__main__",
    "ignore::DeprecationWarning",
    "ignore:.* is an Item subclass and should not be a collector.*:pytest.PytestWarning"
]


[tool.ipdb]
context=5

[tool.isort]
profile = "black"

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]
disable_warnings = ["no-data-collected"]

[tool.coverage.report]
fail_under = 80

[tool.mypy]
warn_unused_ignores = true
warn_redundant_casts = true
show_error_codes = true
ignore_missing_imports = true
disallow_untyped_defs = true
disable_error_code = ["attr-defined", "var-annotated"]